<a href="https://colab.research.google.com/github/AbhayK007/ML-Algorithms/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

creating numpy array


In [ ]:
size=10;
list1=np.arange(size)
list2=np.arange(size)

sum= [(x+y) for x,y in zip(list1,list2)] #or sum= list1 + list2
product = list1*list2
dot=list1.dot(list2)

print(list1)
print(product)
print(dot)
print(sum)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
285
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


.ndim is used to get dimensions of array

In [ ]:
l1=np.array([[[1,2],[4,6]],[[5,7],[5,2]]])
print(l1.ndim)
print(l1.shape)
print(l1.size)
l1[1][0][1]

3
(2, 2, 2)
8


7

In [ ]:
zero = np.zeros((3,4))
one = np.ones((3,4))
one
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.linspace(1,10,19)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
l1.shape

(2, 2, 2)

In [ ]:
l2= np.array([[2,1],[2,6]])
l2.shape

(2, 2)

In [ ]:
l2.reshape(4,1)

array([[2],
       [1],
       [2],
       [6]])

In [ ]:
l2.ravel()

array([2, 1, 2, 6])

In [ ]:
l2

array([[2, 1],
       [2, 6]])

In [ ]:
l2[0:2,1]

array([1, 6])

In [ ]:
l2[-1]

array([2, 6])

In [ ]:
l2[:,-1]

array([1, 6])

In [ ]:
l3=np.arange(1,5).reshape(2,2)
l3

array([[1, 2],
       [3, 4]])

In [ ]:
l2

array([[2, 1],
       [2, 6]])

In [ ]:
np.vstack((l2,l3))

array([[2, 1],
       [2, 6],
       [1, 2],
       [3, 4]])

In [ ]:
h=np.hstack((l2,l3))
h

array([[2, 1, 1, 2],
       [2, 6, 3, 4]])

In [ ]:
L2=np.hsplit(h,2)[0]
L2

array([[2, 1],
       [2, 6]])

In [ ]:
L3=np.hsplit(h,2)[1]
L3

array([[1, 2],
       [3, 4]])

In [ ]:
h

array([[2, 1, 1, 2],
       [2, 6, 3, 4]])

In [ ]:
gthan3 = h>3
print(gthan3)
h[gthan3]

[[False False False False]
 [False  True False  True]]


array([6, 4])

In [ ]:
h[gthan3]=0
h

array([[2, 1, 1, 2],
       [2, 0, 3, 0]])